import "./globals.css";
import ReduxProvider from "./components/ReduxProvider";
import Navbar from "./components/common/Navbar";
import Footer from "./components/common/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReduxProvider>

          <Navbar/>
          {children}
          <Footer/>
        </ReduxProvider>
      </body>
    </html>
  );
}
